version: '2.1'

services:
  spark-master:
    image: bde2020/spark-master:2.4.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - ENABLE_INIT_DAEMON=false
#      - INIT_DAEMON_STEP=setup_spark
#      - "constraint:node==192.168.1.175"
  spark-worker-1:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - ENABLE_INIT_DAEMON=false
      - "SPARK_MASTER=spark://spark-master:7077"
#      - "constraint:node==192.168.1.175"


# docker pull registry.cn-hangzhou.aliyuncs.com/mengjieguo/spark-app-3
  spark-app-1:
    image: bde/spark-app-3
    container_name: spark-app-1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - "./entrypoint.py:/app/entrypoint.py"
    environment:
      - ENABLE_INIT_DAEMON=false
      - "SPARK_MASTER=spark://spark-master:7077"
