version: '2.1'

services:

  spark-app-1:
    image: bde/spark-app
    container_name: spark-app-1
#    depends_on:
#      - spark-master
    ports:
      - "8081:8081"
    environment:
      - ENABLE_INIT_DAEMON=false
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==192.168.1.175"
